### ISSUE TITLE
tables with zero rows hang the TablePlus database client

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe-postgres-fdw#10]
I am seeing a problem for tables with zero rows. They work fine in the steampipe CLI, but they currently hang the TablePlus database client. Specifically, it seems to be expecting more rows to be returned and is waiting for them. It works well when there are any actual rows. Seems like the zero rows case specifically is causing it to wait indefinitely. I'm not sure why...

**Comment by e-gineer** [comment]
@kaidaguerre I have not seen this issue for a long time. I believe it can be closed?
