### ISSUE TITLE
Crash when joining  `ipstack_ip` table on `ip` 

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-postgres-fdw#29]
The ipstack_ip.ip column is not REQUIRED, but it changes the behavior when specified (specifying 'where' on the key returns entirely different result, not a subset).  Regardless, this query causes a crash:

```sql
select 
    eni.network_interface_id,
    eni.description,
    eni.association_public_ip,
    eni.private_ip_address,
    ipstack_ip.*
from 
    aws_ec2_network_interface as eni,
    ipstack_ip
where 
        ipstack_ip.ip = eni.private_ip_address
```
Note that doing `EXPLAIN` on the query ALSO crashes.

FYI - this is when using latest `main` in SDK:
```
module github.com/turbot/steampipe-plugin-ipstack

go 1.15

require (
	github.com/qioalice/ipstack v1.0.1
	github.com/turbot/steampipe-plugin-sdk v0.2.2
)

replace github.com/turbot/steampipe-plugin-sdk => github.com/turbot/steampipe-plugin-sdk v0.2.0-rc.1.0.20210310144957-7f411b3b94fe
```

**Comment by kaidaguerre** [comment]
fixed on quals branch by https://github.com/turbot/steampipe-postgres-fdw/commit/05e0369629d054eeeb9dbe89937ab74bf4b20e23
