### ISSUE TITLE
Steampipe fails when connecting to insecure OpenTelemetry endpoints

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe-postgres-fdw#419]
telemetry.Init service 'steampipe-postgres-fdw', tracingEnabled: true, metricsEnabled: true
panic: failed to initialise telemetry: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials)

**Comment by pskrbasu** [comment]
Steampipe issue: https://github.com/turbot/steampipe/issues/4096
Plugin SDK fix: https://github.com/turbot/steampipe-plugin-sdk/pull/694

**Comment by pskrbasu** [comment]
https://github.com/turbot/steampipe-plugin-sdk/commit/2f7e8e2ac845391dc0cd8a8b7064ed03f7920269

**Comment by Sangamesh-ts** [comment]
@pskrbasu  Still seeing issue . 
ENV set 

```
export STEAMPIPE_OTEL_INSECURE=true
export STEAMPIPE_OTEL_LEVEL=ALL
 export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:16686/
```
```steampipe -v
Steampipe v0.21.7
➜  .steampipe steampipe query
Welcome to Steampipe v0.21.7
For more information, type .help
Warning: grpc: no transport security set (use grpc.WithTransportCredentials(insecure.NewCredentials()) explicitly or set credentials)
```

**Comment by pskrbasu** [comment]
@Sangamesh-ts Are you seeing just the warning or is it still failing for you? I tried the same and it seems to be working for me(I get the warning as well). I can see the spans getting collected.
