### ISSUE TITLE
Problems with Postgres FDW

### ISSUE THREAD

**Issue by raeudigerRaeffi** [turbot/steampipe-postgres-fdw#434]
Dockerfile of Postgres postgres:14.11

**To reproduce**
Using the install script (https://raw.githubusercontent.com/turbot/steampipe-postgres-fdw/main/scripts/steampipe_postgres_installer.sh) to install hubspot latest 
Running "CREATE EXTENSION IF NOT EXISTS steampipe_postgres_hubspot" gives the following error:
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

The DB is displaying the following error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7facfecdc196]

goroutine 1 [running]:
github.com/turbot/steampipe-postgres-fdw/hub.(*hubBase).getServerCacheEnabled(0x3c0007bfbf8?)
        /home/runner/work/steampipe-plugin-hubspot/steampipe-plugin-hubspot/work/hub/hub_base.go:518 +0x56
github.com/turbot/steampipe-postgres-fdw/hub.newLocalHub()
        /home/runner/work/steampipe-plugin-hubspot/steampipe-plugin-hubspot/work/hub/hub_local.go:39 +0x146
github.com/turbot/steampipe-postgres-fdw/hub.CreateHub()
        /home/runner/work/steampipe-plugin-hubspot/steampipe-plugin-hubspot/work/hub/hub_create.go:35 +0x8d
main.init.0()
        /home/runner/work/steampipe-plugin-hubspot/steampipe-plugin-hubspot/work/fdw.go:58 +0x265
2024-03-02 10:15:34.662 UTC [1] LOG:  server process (PID 71) was terminated by signal 6: Aborted
2024-03-02 10:15:34.662 UTC [1] DETAIL:  Failed process was running: CREATE EXTENSION IF NOT EXISTS steampipe_postgres_hubspot;
2024-03-02 10:15:34.662 UTC [1] LOG:  terminating any other active server processes
2024-03-02 10:15:34.664 UTC [1] LOG:  all server processes terminated; reinitializing

**Comment by yemaney** [comment]
I saw a similar issue after installing the aws plugin in the official postgres docker image.

**Comment by pskrbasu** [comment]
Hey @yemaney Is this something recurring? I'll try installing it in the official Postgres docker image and see if I can reproduce this.

**Comment by pskrbasu** [comment]
@raeudigerRaeffi @yemaney We have identified the bug and the fix will be available shortly. Thanks!
