### ISSUE TITLE
Cache not working when using as standalone extension

### ISSUE THREAD

**Issue by miguelbranco80** [turbot/steampipe-postgres-fdw#480]
When using steampipe-postgres-fdw as a standalone extension, the cache does not seem to be working.

When running in TRACE mode, there's an indication that the connection cache was cleared. This is visible if we do multiple queries using e.g. `psql`. There is a significant delay due to this. Even with STEAMPIPE_CACHE off, queries are slower than they should be (as I believe there's some upfront work - schema caches? - that is also re-done everytime.)

While digging over the codebase of [hub_local.go](https://github.com/turbot/steampipe-postgres-fdw/blob/develop/hub/hub_local.go) I noticed that `UpdateConnectionConfig` was being called everytime, and this lead to the connection cache being cleared [here](https://github.com/turbot/steampipe-postgres-fdw/blob/ac602a807aeb15e2c7965da8b507f9912fc7b35f/hub/hub_local.go#L80).

As an experiment, I tried modifying the `UpdateConnectionConfig` to add the an `if` statement:
```go
func (l *HubLocal) UpdateConnectionConfig(connectionName, configString string) error {
	log.Printf("[INFO] HubLocal UpdateConnectionConfig: connection: %s, config: %s", connectionName, configString)

   // BEGIN MODIFICATION
    if conn, ok := l.connections[connectionName]; ok && conn.Config == configString {
        return nil
    }
   // END MODIFICATION

   [ ...]
```

By adding the `if` statement, we prevent the call to `l.plugin.UpdateConnectionConfigs`, which triggers the connection cache invalidation.

I'm happy to contribute a PR with the change, but would need to understand first if this is going in the right direction. I am not yet very familiar with the codebase and just began exploring it in the past few days.

**Comment by pskrbasu** [comment]
Thank you for raising this issue @miguelbranco80.

We have found the fix for this, basically the `ProcessImportForeignSchemaOptions` is unnecessary [here](https://github.com/turbot/steampipe-postgres-fdw/blob/ac602a807aeb15e2c7965da8b507f9912fc7b35f/fdw.go#L142) (which led to the clearing of connection cache).
